- name: Instalación Grafana Alloy + config dinámica por JBoss
  hosts: all
  gather_facts: no

  vars:
    alloy_install_dir: "C:\\Program Files\\GrafanaLabs\\Alloy"
    alloy_exe: "Alloy_agente.exe"
    alloy_config_file: "config.alloy"

    alloy_download_url: "http://10.62.64.22:30080/files"
    jboss_base_path: "C:\\Temenos\\R18\\3rdParty\\As"

  tasks:

  # ------------------------------------------------------------
  # 1. Buscar carpetas JBoss
  # ------------------------------------------------------------
  - name: Buscar instancias JBoss
    win_find:
      paths: "{{ jboss_base_path }}"
      file_type: directory
      patterns: "T24Prod*"
    register: jboss_dirs

  - name: Validar rutas encontradas
    debug:
      var: jboss_dirs.files

  # ------------------------------------------------------------
  # 2. Extraer nombres de JBoss
  # ------------------------------------------------------------
  - name: Extraer nombres de JBoss
    set_fact:
      jboss_instances: >-
        {{ jboss_dirs.files
           | map(attribute='path')
           | map('basename')
           | list }}

  - name: Mostrar nombres de JBoss
    debug:
      msg: "JBoss detectados: {{ jboss_instances }}"

  - name: Fallar si no se detectan JBoss
    fail:
      msg: "No se detectaron instancias JBoss en {{ jboss_base_path }}"
    when: jboss_instances | length == 0

  # ------------------------------------------------------------
  # 3. Crear directorio de instalación
  # ------------------------------------------------------------
  - name: Crear directorio de instalación de Alloy
    win_file:
      path: "{{ alloy_install_dir }}"
      state: directory

  # ------------------------------------------------------------
  # 4. Verificar binario Alloy
  # ------------------------------------------------------------
  - name: Verificar si Alloy ya existe
    win_stat:
      path: "{{ alloy_install_dir }}\\{{ alloy_exe }}"
    register: alloy_bin

  # ------------------------------------------------------------
  # 5. Descargar Alloy desde Nginx (si no existe)
  # ------------------------------------------------------------
  - name: Descargar ejecutable de Alloy
    win_get_url:
      url: "{{ alloy_download_url }}/{{ alloy_exe }}"
      dest: "{{ alloy_install_dir }}\\{{ alloy_exe }}"
    when: not alloy_bin.stat.exists

  - name: Confirmar descarga de Alloy
    debug:
      msg: "Alloy descargado correctamente"
    when: alloy_bin.stat.exists

  # ------------------------------------------------------------
  # 5. Instalar Grafana Alloy (ejecutar instalador)
  # ------------------------------------------------------------
  - name: Instalar Grafana Alloy
    win_package:
      path: "{{ alloy_install_dir }}\\{{ alloy_exe }}"
      arguments: "/S"
      state: present

    - name: Verificar binario de Alloy instalado
    win_stat:
      path: "C:\\Program Files\\GrafanaLabs\\Alloy\\alloy.exe"
    register: alloy_installed

  - name: Confirmar instalación de Alloy
    debug:
      msg: "Grafana Alloy instalado correctamente"
    when: alloy_installed.stat.exists


  # ------------------------------------------------------------
  # 6. Generar config.alloy dinámico
  # ------------------------------------------------------------
  - name: Crear config.alloy dinámico
    win_template:
      src: config.alloy.j2
      dest: "{{ alloy_install_dir }}\\{{ alloy_config_file }}"

  # ------------------------------------------------------------
  # 7. Mostrar config generada (solo lectura)
  # ------------------------------------------------------------
  - name: Mostrar contenido de config.alloy
    win_shell: |
      type "{{ alloy_install_dir }}\\{{ alloy_config_file }}"
    register: alloy_config_out

  - name: Mostrar salida de config.alloy
    debug:
      var: alloy_config_out.stdout
