---
- name: Instalación Grafana Alloy + config dinámica por JBoss
  hosts: all
  gather_facts: no

  vars:
    alloy_install_dir: "C:\\Program Files\\GrafanaLabs\\Alloy"
    alloy_zip: "Alloy_agente.zip"
    alloy_exe: "Alloy_agente.exe"
    alloy_config_file: "config.alloy"

    alloy_download_url: "https://github.com/mfenacoac/awx-plabooks/releases/download/Alloy"

    jboss_base_path: "C:\\Temenos\\R18\\3rdParty\\As"

  tasks:

  # ------------------------------------------------------------
  # 1. Buscar carpetas JBoss
  # ------------------------------------------------------------
  - name: Buscar instancias JBoss
    ansible.windows.win_find:
      paths: "{{ jboss_base_path }}"
      file_type: directory
      patterns: "T24*"   # Patron de busqueda
    register: jboss_dirs

  - name: Inicializar lista de JBoss
    set_fact:
      jboss_instances: []

  - name: Construir lista dinámica de JBoss
    set_fact:
      jboss_instances: "{{ jboss_instances + [ {
        'name': item.filename,
        'log_path': item.path ~ '\\standalone\\log\\server.log'
      } ] }}"
    loop: "{{ jboss_dirs.files }}"

  - name: Mostrar instancias JBoss detectadas
    debug:
      var: jboss_instances

  - name: Fallar si no se detectan JBoss
    fail:
      msg: "No se detectaron instancias JBoss en {{ jboss_base_path }}"
    when: jboss_instances | length == 0

  # ------------------------------------------------------------
  # 2. Crear directorio de instalación
  # ------------------------------------------------------------
  - name: Crear directorio de instalación de Alloy
    ansible.windows.win_file:
      path: "{{ alloy_install_dir }}"
      state: directory

  # ------------------------------------------------------------
  # 3. Descargar Alloy ZIP desde GitHub (solo AWX necesita internet)
  # ------------------------------------------------------------
  - name: Descargar Alloy en el controlador AWX
    delegate_to: localhost
    get_url:
      url: "{{ alloy_download_url }}/{{ alloy_zip }}"
      dest: "/tmp/{{ alloy_zip }}"

  - name: Copiar Alloy al servidor Windows
    ansible.windows.win_copy:
      src: "/tmp/{{ alloy_zip }}"
      dest: "{{ alloy_install_dir }}\\{{ alloy_zip }}"

  # ------------------------------------------------------------
  # 4. Descomprimir Alloy
  # ------------------------------------------------------------
  - name: Descomprimir Alloy con PowerShell
    ansible.windows.win_shell: >
      Expand-Archive -Path "{{ alloy_install_dir }}\\{{ alloy_zip }}" -DestinationPath "{{ alloy_install_dir }}" -Force
    args:
      creates: "{{ alloy_install_dir }}\\{{ alloy_exe }}"

  # ------------------------------------------------------------
  # 5. Ejecutar instalador de Alloy
  # ------------------------------------------------------------
  - name: Ejecutar instalador de Grafana Alloy
    ansible.windows.win_shell: >
      Start-Process -FilePath ".\\{{ alloy_exe }}" -ArgumentList "/S" -Wait
    args:
      chdir: "{{ alloy_install_dir }}"
      executable: powershell.exe

  # ------------------------------------------------------------
  # 6. Verificar instalación de Alloy
  # ------------------------------------------------------------
  - name: Verificar servicio Alloy
    ansible.windows.win_service:
      name: Alloy
    register: alloy_service

  - name: Fallar si Alloy no está instalado
    fail:
      msg: "Grafana Alloy no está instalado o el servicio no existe"
    when: not alloy_service.exists

  - name: Asegurar que Alloy esté en ejecución
    ansible.windows.win_service:
      name: Alloy
      state: started
      start_mode: delayed

  # ------------------------------------------------------------
  # 7. Generar config.alloy dinámico
  # ------------------------------------------------------------
  - name: Aplicar config.alloy dinámico
    ansible.windows.win_template:
      src: templates/config.alloy.j2
      dest: "{{ alloy_install_dir }}\\{{ alloy_config_file }}"
      force: yes

  - name: Reiniciar servicio Alloy
    ansible.windows.win_service:
      name: Alloy
      state: restarted

  # ------------------------------------------------------------
  # 8. Mostrar config generada (debug)
  # ------------------------------------------------------------
  - name: Mostrar contenido de config.alloy
    ansible.windows.win_shell: |
      type "{{ alloy_install_dir }}\\{{ alloy_config_file }}"
    register: alloy_config_out

  - name: Mostrar salida de config.alloy
    debug:
      var: alloy_config_out.stdout
