---
- name: Instalación Grafana Alloy + config dinámica por JBoss
  hosts: all
  gather_facts: no

  vars:
    alloy_install_dir: "C:\\Program Files\\GrafanaLabs\\Alloy"
    alloy_exe: "Alloy_agente.exe"
    alloy_config_file: "config.alloy"

    alloy_download_url: "http://10.62.64.22:30080/files"
    jboss_base_path: "C:\\Temenos\\R18\\3rdParty\\As"

  tasks:

  # ------------------------------------------------------------
  # 1. Buscar carpetas JBoss
  # ------------------------------------------------------------
  - name: Buscar instancias JBoss
    ansible.windows.win_find:
      paths: C:\Temenos\R18\3rdParty\As
      file_type: directory
    register: jboss_dirs

  - name: Inicializar lista de JBoss
    set_fact:
      jboss_instances: []

  - name: Construir lista dinámica de JBoss
    set_fact:
      jboss_instances: "{{ jboss_instances + [ {
        'name': item.filename,
        'log_path': item.path ~ '\\standalone\\log\\server.log'
      } ] }}"
    loop: "{{ jboss_dirs.files }}"


  - name: Mostrar instancias JBoss detectadas
    debug:
      var: jboss_instances

  - name: Fallar si no se detectan JBoss
    fail:
      msg: "No se detectaron instancias JBoss en {{ jboss_base_path }}"
    when: jboss_instances | length == 0

  # ------------------------------------------------------------
  # 2. Crear directorio de instalación
  # ------------------------------------------------------------
  - name: Crear directorio de instalación de Alloy
    win_file:
      path: "{{ alloy_install_dir }}"
      state: directory

  # ------------------------------------------------------------
  # 3. Verificar si Alloy ya está descargado
  # ------------------------------------------------------------
  - name: Verificar binario del instalador
    win_stat:
      path: "{{ alloy_install_dir }}\\{{ alloy_exe }}"
    register: alloy_installer

  # ------------------------------------------------------------
  # 4. Descargar Alloy desde Nginx
  # ------------------------------------------------------------
  - name: Descargar instalador de Alloy
    win_get_url:
      url: "{{ alloy_download_url }}/{{ alloy_exe }}"
      dest: "{{ alloy_install_dir }}\\{{ alloy_exe }}"
    when: not alloy_installer.stat.exists

  # ------------------------------------------------------------
  # 5. Ejecutar instalador de Alloy
  # ------------------------------------------------------------
  - name: Ejecutar instalador de Grafana Alloy
    win_shell: >
      Start-Process -FilePath ".\\{{ alloy_exe }}" -ArgumentList "/S" -Wait
    args:
      chdir: "{{ alloy_install_dir }}"
      executable: powershell.exe

  # ------------------------------------------------------------
  # 6. Verificar instalación de Alloy
  # ------------------------------------------------------------
  - name: Verificar servicio Alloy
    win_service:
      name: Alloy
    register: alloy_service

  - name: Fallar si Alloy no está instalado
    fail:
      msg: "Grafana Alloy no está instalado o el servicio no existe"
    when: alloy_service.exists == false

  - name: Asegurar que Alloy esté en ejecución
    win_service:
      name: Alloy
      state: started
      start_mode: delayed

  - name: Aplicar config.alloy personalizado
    win_template:
      src: templates/config.alloy.j2
      dest: "{{ alloy_install_dir }}\\config.alloy"
      force: yes

  - name: Reiniciar servicio Alloy
    win_service:
      name: Alloy
      state: restarted

  # ------------------------------------------------------------
  # 7. Generar config.alloy dinámico
  # ------------------------------------------------------------
  - name: Crear config.alloy dinámico
    win_template:
      src: config.alloy.j2
      dest: "{{ alloy_install_dir }}\\{{ alloy_config_file }}"

  # ------------------------------------------------------------
  # 8. Mostrar config generada (debug)
  # ------------------------------------------------------------
  - name: Mostrar contenido de config.alloy
    win_shell: |
      type "{{ alloy_install_dir }}\\{{ alloy_config_file }}"
    register: alloy_config_out

  - name: Mostrar salida de config.alloy
    debug:
      var: alloy_config_out.stdout
