---
- name: Detener JBoss y limpiar logs
  hosts: all
  gather_facts: no
  tasks:
    - name: Detener JBoss usando jboss-cli
      win_shell: >
        C:\jboss-eap-7.4.0\jboss-eap-7.4\bin\jboss-cli.bat --connect command=:shutdown
      register: shutdown_result

    - name: Esperar 10 segundos para asegurar que JBoss se detuvo
      pause:
        seconds: 10

    - name: Borrar carpetas tmp y data de JBoss
      win_file:
        path: "{{ item }}"
        state: absent
      loop:
        - C:\jboss-eap-7.4.0\jboss-eap-7.4\standalone\tmp
        - C:\jboss-eap-7.4.0\jboss-eap-7.4\standalone\data
        - C:\jboss-eap-7.4.0\jboss-eap-7.4\standalone\log
        - C:\jboss-eap-7.4.0\jboss-eap-7.4\standalone\deployments\*.deployed
        - C:\jboss-eap-7.4.0\jboss-eap-7.4\standalone\deployments\*.undeployed
        - C:\jboss-eap-7.4.0\jboss-eap-7.4\standalone\deployments\*.failed
        - C:\jboss-eap-7.4.0\jboss-eap-7.4\standalone\deployments\*.isdeploying

    #- name: Volver a crear carpeta de logs
      #win_file:
        #path: C:\jboss-eap-7.4.0\jboss-eap-7.4\standalone\log
        #state: directory
