---
- name: Detectar y desinstalar Firefox en Windows
  hosts: all
  gather_facts: no

  tasks:
    - name: Obtener ProductId de Firefox
      ansible.windows.win_shell: |
        (Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*", "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*" |
        Where-Object { $_.DisplayName -like "Mozilla Firefox*" }).PSChildName
      register: firefox_id

    - name: Desinstalar Firefox usando ProductId detectado
      ansible.windows.win_package:
        product_id: "{{ firefox_id.stdout | trim }}"
        state: absent
      when: firefox_id.stdout != ""
