---
- name: Desinstalar Windows Exporter de todos los servidores Windows
  hosts: windows
  gather_facts: no

  tasks:

    - name: Verificar si existe el servicio windows_exporter
      ansible.windows.win_service_facts:
      register: service_facts

    - name: Detener servicio windows_exporter si existe
      ansible.windows.win_service:
        name: windows_exporter
        state: stopped
      when: "'windows_exporter' in service_facts.services"

    - name: Eliminar servicio windows_exporter si existe
      ansible.windows.win_command: 'sc.exe delete windows_exporter'
      when: "'windows_exporter' in service_facts.services"

    - name: Desinstalar Windows Exporter si fue instalado por MSI
      ansible.windows.win_package:
        name: "windows_exporter"
        state: absent
      ignore_errors: yes

    - name: Desinstalar Windows Exporter si fue instalado con Chocolatey
      ansible.windows.win_chocolatey:
        name: windows-exporter
        state: absent
      ignore_errors: yes

    - name: Eliminar carpeta de instalación común
      ansible.windows.win_file:
        path: "C:\\Program Files\\windows_exporter"
        state: absent

    - name: Eliminar carpeta alternativa
      ansible.windows.win_file:
        path: "C:\\windows_exporter"
        state: absent

    - name: Eliminar ejecutable suelto
      ansible.windows.win_file:
        path: "C:\\Program Files\\windows_exporter.exe"
        state: absent

    - name: Eliminar configuraciones antiguas
      ansible.windows.win_file:
        path: "C:\\ProgramData\\windows_exporter"
        state: absent

    - name: Reiniciar winrm
      ansible.windows.win_service:
        name: winrm
        state: restarted
