---
- name: Desinstalar Windows Exporter de todos los servidores Windows
  hosts: windows
  gather_facts: no

  collections:
    - ansible.windows

  tasks:

    - name: Obtener información de servicios
      win_service_facts:
      register: service_facts

    - name: Detener servicio windows_exporter si existe
      win_service:
        name: windows_exporter
        state: stopped
      when: "'windows_exporter' in service_facts.services"

    - name: Eliminar servicio windows_exporter
      win_command: 'sc.exe delete windows_exporter'
      when: "'windows_exporter' in service_facts.services"

    - name: Desinstalar Windows Exporter MSI
      win_package:
        name: "windows_exporter"
        state: absent
      ignore_errors: yes

    - name: Desinstalar Windows Exporter de Chocolatey
      win_chocolatey:
        name: windows-exporter
        state: absent
      ignore_errors: yes

    - name: Eliminar carpeta Program Files
      win_file:
        path: "C:\\Program Files\\windows_exporter"
        state: absent

    - name: Eliminar carpeta raíz
      win_file:
        path: "C:\\windows_exporter"
        state: absent

    - name: Eliminar ejecutable suelto
      win_file:
        path: "C:\\Program Files\\windows_exporter.exe"
        state: absent

    - name: Reiniciar WinRM
      win_service:
        name: winrm
        state: restarted
