---
- name: Desinstalar Firefox en Windows usando UninstallString
  hosts: all
  gather_facts: no

  tasks:
    - name: Obtener UninstallString de Firefox
      ansible.windows.win_shell: |
        (Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*", 
                          "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*" |
        Where-Object { $_.DisplayName -like "Mozilla Firefox*" }).UninstallString
      register: firefox_uninstall

    - name: Limpiar UninstallString (quitar retornos de carro y saltos de línea)
      set_fact:
        firefox_uninstall_clean: "{{ firefox_uninstall.stdout | replace('\r','') | replace('\n','') }}"

    - name: Ejecutar desinstalador de Firefox
      ansible.windows.win_command: '"{{ firefox_uninstall_clean }}" /S'
      when: firefox_uninstall_clean != ""
