---
- name: Desinstalar Firefox en Windows
  hosts: all
  gather_facts: no
  vars:
    firefox_name: "Mozilla Firefox"

  tasks:
    - name: Verificar si Firefox está instalado
      win_shell: |
        $app = Get-WmiObject -Class Win32_Product | Where-Object { $_.Name -eq "{{ firefox_name }}" }
        if ($app) { Write-Output "Installed" } else { Write-Output "NotInstalled" }
      register: firefox_check

    - debug:
        var: firefox_check.stdout

    - name: Desinstalar Firefox si está instalado
      win_shell: |
        Get-WmiObject -Class Win32_Product | Where-Object { $_.Name -eq "{{ firefox_name }}" } | ForEach-Object { $_.Uninstall() }
      when: firefox_check.stdout == "Installed"
