---
- name: Eliminar Firefox de Windows
  hosts: all
  gather_facts: no

  tasks:
    - name: Uninstall 7zip from the exe
  ansible.windows.win_package:
    path: C:\Program Files\Mozilla Firefox\uninstall\helper.exe
    product_id: Mozilla Firefox (x64 es-MX)
    arguments: /S
    state: absent
