---
- name: Desinstalar Windows Exporter
  hosts: {{ win_exporter_srvs }}
  gather_facts: no

  tasks:

    - name: Detener servicio windows_exporter si existe
      win_command: 'sc.exe stop windows_exporter'
      ignore_errors: yes

    - name: Eliminar servicio windows_exporter
      win_command: 'sc.exe delete windows_exporter'
      ignore_errors: yes

    - name: Eliminar carpeta del programa si existe
      win_shell: |
        if (Test-Path "C:\Program Files\windows_exporter") {
            Remove-Item -Path "C:\Program Files\windows_exporter" -Recurse -Force
        }
      ignore_errors: yes

    - name: Confirmar que el servicio ya no existe
      win_command: 'sc.exe query windows_exporter'
      register: result
      failed_when: false

    - debug:
        msg: "Resultado final del estado del servicio: {{ result.stdout }}"
