---
- name: Eliminar Firefox de Windows
  hosts: all
  gather_facts: no

  tasks:
    - name: Desinstalar Firefox (x64 es-MX)
      ansible.windows.win_package:
        path: "C:\Program Files\Mozilla Firefox\uninstall\helper.exe"
        arguments: '/S'
        state: absent

