---
- name: Eliminar Firefox de Windows
  hosts: all
  gather_facts: no

  tasks:

    - name: Desinstalar Firefox vía helper.exe
      win_command: helper.exe /S
      args:
        chdir: 'C:\Program Files\Mozilla Firefox\uninstall'
