---
- name: Instalar Firefox en Windows
  hosts: all
  gather_facts: no
  tasks:

    - name: Crear carpeta temporal
      ansible.windows.win_file:
        path: C:\Temp
        state: directory

    - name: Copiar instalador de Firefox al servidor Windows
      ansible.windows.win_copy:
        src: /home/ansible/instaladores/FirefoxSetup.exe
        dest: C:\Temp\FirefoxSetup.exe

    # - name: Instalar Firefox silenciosamente
    #   ansible.windows.win_package:
    #     path: C:\Temp\FirefoxSetup.exe
    #     arguments: /silent /norestart
    #     state: present
