---
- name: Liberar espacio en disco Windows
  hosts: "{{ (target_host | default('undefined_host')).split(':')[0] }}"
  gather_facts: no
  tasks:
  - name: Validar host recibido
    fail:
      msg: "No es una IP válida: {{ target_host }}"
    when: target_host is not match('^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+(:[0-9]+)?$')
