---
- name: Prueba de conectividad automática desde Grafana
  # Quitamos el "all" y forzamos a que use la variable que manda Grafana
  hosts: "{{ target_host }}"
  gather_facts: false
  
  tasks:
    - name: Ejecutar Ping hacia el servidor Windows
      ansible.windows.win_ping:
