---
- name: Ping Windows Hosts
  hosts: all # Or a specific group from your inventory
  gather_facts: false    # Not required for a simple ping
  tasks:
    - name: Test connectivity to Windows hosts
      ansible.windows.win_ping:
