---
- name: Iniciar Servicios JBoss (Sintaxis cmd /c start)
  hosts: all
  gather_facts: no

  vars:
    # Ruta donde están los archivos .bat (según tu indicación)
    jboss_base_path: "C:\\Temenos\\R18\\3rdParty\\As"

  tasks:
  # ----------------------------------------------------------------------
  # 1. IDENTIFICAR INSTANCIAS (Buscar carpetas T24*)
  # ----------------------------------------------------------------------
  - name: Buscar carpetas de instancias JBoss
    ansible.windows.win_find:
      paths: "{{ jboss_base_path }}"
      file_type: directory
      patterns: "T24*"
    register: jboss_dirs

  # ----------------------------------------------------------------------
  # 2. ARRANQUE CON LA SINTAXIS EXACTA SOLICITADA
  # ----------------------------------------------------------------------
  - name: Iniciar JBoss
    ansible.windows.win_command: >
      cmd /c start {{ jboss_base_path }}\JBoss_{{ item.filename }}_R20.bat
    args:
      # Opcional: aseguramos que se ejecute desde la carpeta base por si el script usa rutas relativas
      chdir: "{{ jboss_base_path }}"
    # Async y Poll en 0 para desconectar y dejar corriendo en background
    async: 10
    poll: 0
    loop: "{{ jboss_dirs.files }}"
    when: jboss_dirs.matched > 0
