---
- name: Flujo de Mantenimiento JBoss (Stop -> Kill -> Patch -> Start)
  hosts: all
  gather_facts: no

  vars:
    jboss_base_path: "C:\\Temenos\\R18\\3rdParty\\As"
    
    # ---------------------------------------------------------
    # CONFIGURACIÓN OPENTELEMETRY
    # ---------------------------------------------------------
    otel_config_block: |
      rem ========================================
      rem OpenTelemetry Java Agent - PRODUCCIÓN
      rem JBoss: %JBOSS_INSTANCE_NAME%
      rem ========================================
      set "JAVA_OPTS=%JAVA_OPTS% -javaagent:C:\telemetry\opentelemetry-javaagent.jar"
      rem Información del servicio
      set "JAVA_OPTS=%JAVA_OPTS% -Dotel.service.name=JBOSS-APPL"
      set "JAVA_OPTS=%JAVA_OPTS% -Dotel.resource.attributes=service.name=JBOSS-APPL,service.version=7.2,deployment.environment=production,client=APPL,host.name=%COMPUTERNAME%,jboss.instance=%JBOSS_INSTANCE_NAME%"
      rem Endpoint local de Alloy
      set "JAVA_OPTS=%JAVA_OPTS% -Dotel.exporter.otlp.endpoint=http://127.0.0.1:4318"
      set "JAVA_OPTS=%JAVA_OPTS% -Dotel.exporter.otlp.protocol=http/protobuf"
      rem Exportadores
      set "JAVA_OPTS=%JAVA_OPTS% -Dotel.traces.exporter=otlp"
      set "JAVA_OPTS=%JAVA_OPTS% -Dotel.metrics.exporter=otlp"
      set "JAVA_OPTS=%JAVA_OPTS% -Dotel.logs.exporter=otlp"
      rem Logs silenciosos
      set "JAVA_OPTS=%JAVA_OPTS% -Dotel.javaagent.debug=false"

  tasks:
  # ----------------------------------------------------------------------
  # 1. IDENTIFICACIÓN DE INSTANCIAS
  # ----------------------------------------------------------------------
  - name: Identificar instancias JBoss
    ansible.windows.win_find:
      paths: "{{ jboss_base_path }}"
      file_type: directory
      patterns: "T24*"
    register: jboss_dirs

  # ----------------------------------------------------------------------
  # 2. APAGADO GRACEFUL (Intenta apagar bien primero)
  # ----------------------------------------------------------------------
  - name: Detener instancias JBoss (Graceful Shutdown)
    ansible.windows.win_shell: |
      $batFile = "{{ jboss_base_path }}\JBoss_{{ item.filename }}_R20.bat"
      $cliScript = "{{ item.path }}\bin\jboss-cli.bat"

      # Calcular puerto
      if (Test-Path $batFile) {
          $content = Get-Content $batFile -Raw
          if ($content -match "port-offset=(\d+)") {
              $mgmtPort = 9990 + [int]$matches[1]
          } else { $mgmtPort = 9990 }
      } else { exit 0 }

      # Verificar y Apagar
      if (Test-NetConnection -ComputerName localhost -Port $mgmtPort -InformationLevel Quiet) {
          Write-Host "Apagando {{ item.filename }}..."
          & '$cliScript' --connect --controller=localhost:$mgmtPort command=:shutdown
          Start-Sleep -Seconds 10
      }
    loop: "{{ jboss_dirs.files }}"
    when: jboss_dirs.matched > 0

  # ----------------------------------------------------------------------
  # 3. LIMPIEZA FORZADA (CORREGIDO: Busca por CommandLine)
  # ----------------------------------------------------------------------
  - name: Matar procesos CMD huérfanos de JBoss
    ansible.windows.win_shell: |
      $instanceName = "{{ item.filename }}"
      # Buscamos coincidencias en la ruta del archivo .bat
      $targetScript = "JBoss_$instanceName"
      
      Write-Host "Buscando procesos CMD ejecutando: $targetScript"
      
      # Usamos WMI/CIM para ver la linea de comandos real
      $orphans = Get-CimInstance Win32_Process -Filter "Name = 'cmd.exe'" | Where-Object { $_.CommandLine -like "*$targetScript*" }
      
      if ($orphans) {
          Write-Host "Matando $($orphans.Count) procesos huérfanos..."
          foreach ($proc in $orphans) {
              # Matamos el proceso CMD
              Invoke-CimMethod -InputObject $proc -MethodName Terminate
          }
          Start-Sleep -Seconds 2
      } else {
          Write-Host "No se encontraron procesos CMD colgados."
      }
    loop: "{{ jboss_dirs.files }}"
    when: jboss_dirs.matched > 0

  # ----------------------------------------------------------------------
  # 4. INYECCIÓN DE CONFIGURACIÓN
  # ----------------------------------------------------------------------
  - name: Inyectar configuración OTEL en el .bat
    ansible.windows.win_shell: |
      $batPath = "{{ jboss_base_path }}\JBoss_{{ item.filename }}_R20.bat"
      $instanceName = "{{ item.filename }}"
      
      if (-not (Test-Path $batPath)) { exit 1 }

      $content = Get-Content -Path $batPath -Raw
      
      if ($content -match "OpenTelemetry Java Agent") {
          Write-Host "Config ya existente."
          exit 0
      }

      $configBlock = @"
      {{ otel_config_block }}
      "@
      $configBlock = $configBlock -replace "%JBOSS_INSTANCE_NAME%", $instanceName

      $targetLineText = "CALL %JBOSS_HOME%\bin\standalone.bat"
      $regexPattern = "(?m)^[\t ]*" + [regex]::Escape($targetLineText)
      $regex = [regex]$regexPattern

      if ($regex.IsMatch($content)) {
          $newContent = $regex.Replace($content, "$configBlock`r`n`$0", 1)
          Copy-Item $batPath "$batPath.bak" -Force
          Set-Content -Path $batPath -Value $newContent
          Write-Host "PATCH APLICADO"
      }
    loop: "{{ jboss_dirs.files }}"
    when: jboss_dirs.matched > 0

  # ----------------------------------------------------------------------
  # 5. ARRANQUE NUEVO
  # ----------------------------------------------------------------------
  - name: Iniciar JBoss (Modo NOPAUSE)
    ansible.windows.win_command: >
      cmd /c "set NOPAUSE=true && start {{ jboss_base_path }}\JBoss_{{ item.filename }}_R20.bat"
    args:
      chdir: "{{ jboss_base_path }}"
    async: 10
    poll: 0
    loop: "{{ jboss_dirs.files }}"
    when: jboss_dirs.matched > 0
