---
- name: Inyectar configuración OpenTelemetry en scripts de JBoss
  hosts: all
  gather_facts: no

  vars:
    jboss_base_path: "C:\\Temenos\\R18\\3rdParty\\As"
    # Definimos el bloque de configuración. Nota: Usamos `r`n para saltos de línea en PowerShell
    otel_config_block: |
      rem ========================================
      rem OpenTelemetry Java Agent - PRODUCCIÓN
      rem JBoss: %JBOSS_INSTANCE_NAME%
      rem ========================================
      set "JAVA_OPTS=%JAVA_OPTS% -javaagent:C:\telemetry\opentelemetry-javaagent.jar"
      rem Información del servicio
      set "JAVA_OPTS=%JAVA_OPTS% -Dotel.service.name=JBOSS-APPL"
      set "JAVA_OPTS=%JAVA_OPTS% -Dotel.resource.attributes=service.name=JBOSS-APPL,service.version=7.2,deployment.environment=production,client=APPL,host.name=%COMPUTERNAME%,jboss.instance=%JBOSS_INSTANCE_NAME%"
      rem Endpoint local de Alloy
      set "JAVA_OPTS=%JAVA_OPTS% -Dotel.exporter.otlp.endpoint=http://127.0.0.1:4318"
      set "JAVA_OPTS=%JAVA_OPTS% -Dotel.exporter.otlp.protocol=http/protobuf"
      rem Exportadores
      set "JAVA_OPTS=%JAVA_OPTS% -Dotel.traces.exporter=otlp"
      set "JAVA_OPTS=%JAVA_OPTS% -Dotel.metrics.exporter=otlp"
      set "JAVA_OPTS=%JAVA_OPTS% -Dotel.logs.exporter=otlp"
      rem Correlación de logs
      set "JAVA_OPTS=%JAVA_OPTS% -Dotel.instrumentation.log4j-appender.experimental.capture-mdc-attributes=*"
      set "JAVA_OPTS=%JAVA_OPTS% -Dotel.instrumentation.logback-appender.experimental.capture-mdc-attributes=*"
      rem Logs silenciosos
      set "JAVA_OPTS=%JAVA_OPTS% -Dotel.javaagent.debug=false"

  tasks:
  # 1. Buscamos las carpetas (Igual que antes)
  - name: Identificar instancias JBoss (Patrón T24*)
    ansible.windows.win_find:
      paths: "{{ jboss_base_path }}"
      file_type: directory
      patterns: "T24*"
    register: jboss_dirs

  # 2. Modificamos el .bat con PowerShell
  - name: Inyectar configuración OTEL en el .bat de inicio
    ansible.windows.win_shell: |
      $batPath = "{{ jboss_base_path }}\JBoss_{{ item.filename }}_R20.bat"
      $instanceName = "{{ item.filename }}"
      
      # 1. Verificamos si el archivo existe
      if (-not (Test-Path $batPath)) {
          Write-Error "El archivo $batPath no existe."
          exit 1
      }

      # 2. Leemos el contenido
      $content = Get-Content -Path $batPath -Raw
      
      # 3. Verificamos si ya tiene la configuración (Idempotencia)
      if ($content -match "OpenTelemetry Java Agent") {
          Write-Host "La configuración ya existe en $instanceName. Omitiendo."
          exit 0
      }

      # 4. Preparamos el bloque a inyectar (Reemplazamos el placeholder del nombre)
      $configBlock = @"
      {{ otel_config_block }}
      "@
      $configBlock = $configBlock -replace "%JBOSS_INSTANCE_NAME%", $instanceName

      # 5. Definimos la línea objetivo donde insertar ANTES
      # Buscamos la línea que empieza con CALL %JBOSS_HOME...
      $targetLine = "CALL %JBOSS_HOME%\bin\standalone.bat"
      
      # Escapamos caracteres especiales para Regex
      $targetRegex = [regex]::Escape($targetLine)

      # 6. Realizamos el reemplazo
      if ($content -match $targetRegex) {
          # Insertamos el bloque + salto de línea + la línea original
          $newContent = $content -replace $targetRegex, "$configBlock`r`n$targetLine"
          
          # Guardamos backup
          Copy-Item $batPath "$batPath.bak" -Force
          
          # Guardamos archivo modificado
          Set-Content -Path $batPath -Value $newContent
          Write-Host "Configuración inyectada correctamente en $instanceName"
      } else {
          Write-Warning "No se encontró la línea de arranque 'CALL %JBOSS_HOME%...' en $batPath"
      }
    loop: "{{ jboss_dirs.files }}"
    when: jboss_dirs.matched > 0
