---
- name: Inyectar configuración OpenTelemetry en scripts de JBoss
  hosts: all
  gather_facts: yes  # Necesario si quieres usar ansible_host, si usas localhost no hace falta.

  vars:
    jboss_base_path: "C:\\Temenos\\R18\\3rdParty\\As"
    # Definimos el bloque de texto como una variable para mantener el código limpio
    otel_config_block: |
      rem ========================================
      rem OpenTelemetry Java Agent - PRODUCCIÓN
      rem JBoss: {{ item.filename }}
      rem ========================================
      set "JAVA_OPTS=%JAVA_OPTS% -javaagent:C:\telemetry\opentelemetry-javaagent.jar"
      rem Información del servicio
      set "JAVA_OPTS=%JAVA_OPTS% -Dotel.service.name=JBOSS-APPL"
      set "JAVA_OPTS=%JAVA_OPTS% -Dotel.resource.attributes=service.name=JBOSS-APPL,service.version=7.2,deployment.environment=production,client=APPL,host.name=%COMPUTERNAME%,jboss.instance={{ item.filename }}"
      rem Endpoint local de Alloy
      set "JAVA_OPTS=%JAVA_OPTS% -Dotel.exporter.otlp.endpoint=http://127.0.0.1:4318"
      set "JAVA_OPTS=%JAVA_OPTS% -Dotel.exporter.otlp.protocol=http/protobuf"
      rem Exportadores
      set "JAVA_OPTS=%JAVA_OPTS% -Dotel.traces.exporter=otlp"
      set "JAVA_OPTS=%JAVA_OPTS% -Dotel.metrics.exporter=otlp"
      set "JAVA_OPTS=%JAVA_OPTS% -Dotel.logs.exporter=otlp"
      rem Correlación de logs
      set "JAVA_OPTS=%JAVA_OPTS% -Dotel.instrumentation.log4j-appender.experimental.capture-mdc-attributes=*"
      set "JAVA_OPTS=%JAVA_OPTS% -Dotel.instrumentation.logback-appender.experimental.capture-mdc-attributes=*"
      rem Logs silenciosos
      set "JAVA_OPTS=%JAVA_OPTS% -Dotel.javaagent.debug=false"

  tasks:

  # 1. Buscamos las carpetas para saber los nombres de las instancias (Igual que el anterior)
  - name: Identificar instancias JBoss (Patrón T24*)
    ansible.windows.win_find:
      paths: "{{ jboss_base_path }}"
      file_type: directory
      patterns: "T24*"
    register: jboss_dirs

  # 2. Modificamos el .bat correspondiente a cada carpeta encontrada
  - name: Inyectar configuración OTEL en el .bat de inicio
    ansible.windows.win_blockinfile:
      # Construimos la ruta del .bat asumiendo que está en la raíz de 'As'
      path: "{{ jboss_base_path }}\\JBoss_{{ item.filename }}_R20.bat"
      
      # Usamos marcadores personalizados tipo REM para que no rompan el script batch
      marker: "rem {mark} CONFIGURACION OPENTELEMETRY ANSIBLE"
      
      # Esto es lo más importante: Busca la línea que ejecuta el servidor
      # e inserta el bloque JUSTO ANTES de ella.
      insertbefore: "^CALL %JBOSS_HOME%\\\\bin\\\\standalone.bat"
      
      # El contenido que definimos arriba en 'vars'
      block: "{{ otel_config_block }}"
      
      # Crea una copia de seguridad del .bat original por si acaso (ej: .bat.20231025.bak)
      backup: yes
    
    # Iteramos sobre las carpetas encontradas
    loop: "{{ jboss_dirs.files }}"
    
    # Solo intentamos modificar si el archivo .bat realmente existe
    when: jboss_dirs.matched > 0
