---
- name: Flujo de Mantenimiento JBoss (Stop -> Kill -> Patch -> Start)
  hosts: all
  gather_facts: no

  vars:
    jboss_base_path: "C:\\Temenos\\R18\\3rdParty\\As"
    
    # ---------------------------------------------------------
    # CONFIGURACIÓN OPENTELEMETRY + FIX CIERRE CMD
    # ---------------------------------------------------------
    otel_config_block: |
      rem ========================================
      rem OpenTelemetry Java Agent - PRODUCCIÓN
      rem JBoss: %JBOSS_INSTANCE_NAME%
      rem ========================================
      set "JAVA_OPTS=%JAVA_OPTS% -javaagent:C:\telemetry\opentelemetry-javaagent.jar"
      rem Información del servicio
      set "JAVA_OPTS=%JAVA_OPTS% -Dotel.service.name=JBOSS-APPL"
      set "JAVA_OPTS=%JAVA_OPTS% -Dotel.resource.attributes=service.name=JBOSS-APPL,service.version=7.2,deployment.environment=production,client=APPL,host.name=%COMPUTERNAME%,jboss.instance=%JBOSS_INSTANCE_NAME%"
      rem Endpoint local de Alloy
      set "JAVA_OPTS=%JAVA_OPTS% -Dotel.exporter.otlp.endpoint=http://127.0.0.1:4318"
      set "JAVA_OPTS=%JAVA_OPTS% -Dotel.exporter.otlp.protocol=http/protobuf"
      rem Exportadores
      set "JAVA_OPTS=%JAVA_OPTS% -Dotel.traces.exporter=otlp"
      set "JAVA_OPTS=%JAVA_OPTS% -Dotel.metrics.exporter=otlp"
      set "JAVA_OPTS=%JAVA_OPTS% -Dotel.logs.exporter=otlp"
      rem Logs silenciosos
      set "JAVA_OPTS=%JAVA_OPTS% -Dotel.javaagent.debug=false"
      
      rem ========================================
      rem FIX: Cierre automatico de ventana
      rem ========================================
      set NOPAUSE=true

  tasks:
  # ----------------------------------------------------------------------
  # 1. IDENTIFICACIÓN DE INSTANCIAS
  # ----------------------------------------------------------------------
  - name: Identificar instancias JBoss (Carpetas T24*)
    ansible.windows.win_find:
      paths: "{{ jboss_base_path }}"
      file_type: directory
      patterns: "T24*"
    register: jboss_dirs

  # ----------------------------------------------------------------------
  # 2. APAGADO GRACEFUL INTELIGENTE
  # ----------------------------------------------------------------------
  - name: Detener instancias JBoss (Si el puerto responde)
    ansible.windows.win_shell: |
      $instancePath = "{{ item.path }}"
      $instanceName = "{{ item.filename }}"
      $batFile = "{{ jboss_base_path }}\JBoss_{{ item.filename }}_R20.bat"
      $cliScript = "$instancePath\bin\jboss-cli.bat"

      Write-Host "Verificando estado de $instanceName..."

      if (Test-Path $batFile) {
          $content = Get-Content $batFile -Raw
          if ($content -match "port-offset=(\d+)") {
              $offset = [int]$matches[1]
              $mgmtPort = 9990 + $offset
          } else {
              $mgmtPort = 9990
          }
      } else {
          Write-Warning "No se encontró el BAT de arranque. Omitiendo shutdown."
          exit 0
      }

      $connection = Test-NetConnection -ComputerName localhost -Port $mgmtPort -InformationLevel Quiet
      
      if ($connection) {
          Write-Host "   -> ESTATUS: ACTIVO (Puerto $mgmtPort). Iniciando apagado graceful..."
          $shutdownCmd = "& '$cliScript' --connect --controller=localhost:$mgmtPort command=:shutdown"
          try {
              Invoke-Expression $shutdownCmd
              Start-Sleep -Seconds 10
          } catch {
              Write-Warning "Error al enviar comando de apagado."
          }
      } else {
          Write-Host "   -> ESTATUS: DETENIDO (Puerto $mgmtPort cerrado). Continuando..."
      }
    loop: "{{ jboss_dirs.files }}"
    when: jboss_dirs.matched > 0

  # ----------------------------------------------------------------------
  # 3. LIMPIEZA DE VENTANAS "CONGELADAS"
  # ----------------------------------------------------------------------
  - name: Matar ventanas CMD antiguas esperando Enter
    ansible.windows.win_shell: |
      $instanceName = "{{ item.filename }}"
      $targetTitle = "*R20_$instanceName*"
      
      Write-Host "Buscando ventanas congeladas con título: $targetTitle"
      
      $processes = Get-Process | Where-Object { $_.MainWindowTitle -like $targetTitle }
      
      if ($processes) {
          Write-Host "Matando ventana CMD de $instanceName..."
          $processes | Stop-Process -Force
          Start-Sleep -Seconds 2
      } else {
          Write-Host "No se encontraron ventanas congeladas."
      }
    loop: "{{ jboss_dirs.files }}"
    when: jboss_dirs.matched > 0

# ----------------------------------------------------------------------
  # 4. INYECCIÓN DE CONFIGURACIÓN + FIX EXIT (PERFECCIONADO)
  # ----------------------------------------------------------------------
  - name: Inyectar configuración OTEL y arreglar EXIT duplicado
    ansible.windows.win_shell: |
      $batPath = "{{ jboss_base_path }}\JBoss_{{ item.filename }}_R20.bat"
      $instanceName = "{{ item.filename }}"
      
      if (-not (Test-Path $batPath)) {
          Write-Error "El archivo $batPath no existe."
          exit 1
      }

      # --- LÓGICA DE RESTAURACIÓN DE EMERGENCIA ---
      # Si detectamos un archivo roto (exit con argumentos), restauramos backup
      if (Test-Path "$batPath.bak") {
          $currentContent = Get-Content $batPath -Raw
          if ($currentContent -match "exit --server-config") {
             Write-Host "Detectado archivo roto. Restaurando backup..."
             Copy-Item "$batPath.bak" $batPath -Force
          }
      }

      $content = Get-Content -Path $batPath -Raw
      
      # Validamos si ya tiene el parche (IDEMPOTENCIA)
      if ($content -match "OpenTelemetry Java Agent") {
          Write-Host "Configuración ya existente en $instanceName. Omitiendo."
          exit 0
      }

      # Preparar bloque de texto
      $configBlock = @"
      {{ otel_config_block }}
      "@
      $configBlock = $configBlock -replace "%JBOSS_INSTANCE_NAME%", $instanceName

      # --- AQUÍ ESTÁ LA MAGIA PARA EVITAR DOBLE EXIT ---
      $targetLineText = "CALL %JBOSS_HOME%\bin\standalone.bat"
      
      # EXPLICACIÓN DEL REGEX:
      # (?m)        -> Multilínea
      # (^[\t ]*... -> GRUPO 1 ($1): Captura la línea del CALL completa con sus argumentos (.*)
      # (\s+exit)?  -> GRUPO 2: Detecta (y consume) opcionalmente un 'exit' existente al final
      
      $regexPattern = "(?m)(^[\t ]*" + [regex]::Escape($targetLineText) + ".*)(\s+exit)?"
      $regex = [regex]$regexPattern

      if ($regex.IsMatch($content)) {
          # Reemplazamos lo encontrado (CALL + posible exit viejo) 
          # Por: Config + CALL Limpio ($1) + Un solo Exit nuevo
          $newContent = $regex.Replace($content, "$configBlock`r`n`$1`r`nexit", 1)
          
          Copy-Item $batPath "$batPath.bak" -Force
          Set-Content -Path $batPath -Value $newContent
          Write-Host "PATCH APLICADO Y LIMPIADO en $instanceName"
      } else {
          Write-Warning "No se encontró la línea de arranque activa en $batPath"
      }
    loop: "{{ jboss_dirs.files }}"
    when: jboss_dirs.matched > 0

# ----------------------------------------------------------------------
  # 5. ARRANQUE NUEVO
  # ----------------------------------------------------------------------
  - name: Iniciar JBoss (Modo NOPAUSE)
    ansible.windows.win_command: >
      cmd "start {{ jboss_base_path }}\JBoss_{{ item.filename }}_R20.bat"
    args:
      chdir: "{{ jboss_base_path }}"
    async: 10
    poll: 0
    loop: "{{ jboss_dirs.files }}"
    when: jboss_dirs.matched > 0
